Repository MahApps/MahApps.Metro, pull requests merged in 2018-12, with the labels that each got.

#3395 Remove obsolete Styles and Templates
  build.cake
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuSample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Styles/Clean/CleanWindowButtons.xaml
  src/MahApps.Metro/Styles/Colors.xaml
  src/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Controls.Calendar.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.ProgressBar.xaml
  src/MahApps.Metro/Styles/Controls.Slider.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Styles/Controls.ToggleSwitch.xaml
  src/MahApps.Metro/Styles/Controls.TreeView.xaml
  src/MahApps.Metro/Styles/FlatSlider.xaml
  src/MahApps.Metro/Styles/Shared.xaml
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/Themes/DropDownButton.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/Generic.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Breaking Change

#3402 Use Microsoft.Xaml.Behaviors.Wpf instead the System.Windows.Interactivity
  paket.lock
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/FodyWeavers.xml
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/FodyWeavers.xsd
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/paket.references
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/Behaviors/DateTimeNowBehavior.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ColorExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/InteropDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/ShowcaseFlyout.xaml
  src/MahApps.Metro.sln.DotSettings
  src/MahApps.Metro/Actions/CommandTriggerAction.cs
  src/MahApps.Metro/Behaviours/BindableResourceBehavior.cs
  src/MahApps.Metro/Behaviours/DatePickerTextBoxBehavior.cs
  src/MahApps.Metro/Behaviours/PasswordBoxBindingBehavior.cs
  src/MahApps.Metro/Behaviours/StylizedBehaviorCollection.cs
  src/MahApps.Metro/Behaviours/StylizedBehaviors.cs
  src/MahApps.Metro/Behaviours/TabControlSelectFirstVisibleTabBehavior.cs
  src/MahApps.Metro/Behaviours/TiltBehavior.cs
  src/MahApps.Metro/Behaviours/WindowsSettingBehaviour.cs
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
Labels: Breaking Change

#3404 single BooleanToVisibilityConverter naming consistency
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
Labels: CleanUp / Typos

#3405 VS style demo addition
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml.cs
  src/MahApps.Metro/Styles/VS/Colors.xaml
  src/MahApps.Metro/Styles/VS/Window.xaml
Labels: Feature

#3416 Change Dialog Button Styles
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/CustomDialogExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Labels: Breaking Change
