Repository MahApps/MahApps.Metro, pull requests merged in 2018-09, with the labels that each got.

#3317 Drop .NET40
  src/Directory.build.props
  src/Directory.build.targets
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/App.net40.config
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.net40.config
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuSample.xaml.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/Properties/AssemblyInfo.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/TaskEx.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/paket.references
  src/MahApps.Metro/Controls/CommandHelpers.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
  src/MahApps.Metro/Controls/Helper/ComboBoxHelper.cs
  src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/SplitView/SplitViewPaneClosingEventArgs.cs
  src/Mahapps.Metro.Tests/App.net40.config
  src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
  src/Mahapps.Metro.Tests/TestHelpers/AutomationTestBase.cs
  src/Mahapps.Metro.Tests/paket.references
  src/paket.dependencies
  src/paket.lock
Labels: Breaking Change

#3319 (GH-3308) Fix TabItem HeaderFontSize change leads to freeze
  src/MahApps.Metro/Controls/Extensions.cs
  src/MahApps.Metro/Controls/FlipView.cs
  src/MahApps.Metro/Controls/Underline.cs
Labels: Bug

#3322 (GH-3275) Fix TransitioningContentControl vs. ContentControl
  src/MahApps.Metro/Controls/TransitioningContentControl.cs
  src/MahApps.Metro/Themes/TransitioningContentControl.xaml
  src/build.cake
Labels: Bug

#3327 Add appveyor nuget link to readme
  readme.md
Labels: Bug

#3330 TabControl, TabItem enhancement
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuSample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
  src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
  src/MahApps.Metro/Styles/Clean/CleanGroupBox.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.GroupBox.xaml
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
  src/MahApps.Metro/Styles/VS/GroupBox.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/HamburgerMenu.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
  src/MahApps.Metro/Themes/MetroHeader.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
  src/MahApps.Metro/Themes/TransitioningContentControl.xaml
  src/MahApps.Metro/Themes/WindowButtonCommands.xaml
Labels: Feature

#3341 Fix WpfAnalyzers warnings
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuDefault.xaml.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
  src/MahApps.Metro/Controls/TimePicker/TimePickerBase.cs
  src/paket.dependencies
  src/paket.lock
Labels: Internal Refactoring
