Repository MahApps/MahApps.Metro, pull requests merged in 2019-06, with the labels that each got.

#3517 Close dialogs with Alt+F4
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml.cs
Labels: Feature

#3518 (GH-3484) Allow set Dialogs inner content Column GridLength
  src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Labels: Feature

#3519 (GH-3504) Add initial remember checkbox checked
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/LoginDialogSettings.cs
Labels: Feature

#3523 Wraped the demo pages in a scrollviewer for a better user expierience
  GitReleaseManager.yaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ColorExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ProgressBars.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/Sliders.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SplitViewExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TilesExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
  src/MahApps.Metro/Themes/MetroTabControl.xaml
Labels: Improvement

#3526 NumericUpDown: Add a property to control changing value with key Enter
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/Controls/NumericUpDown.cs
  src/MahApps.Metro/Themes/NumericUpDown.xaml
Labels: Feature

#3524 Tab Control Underline Position
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml.cs
  src/MahApps.Metro/Controls/Helper/TabControlHelper.cs
  src/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
Labels: Feature

#3536 Preventing potential re-entrancy issues by delaying confirmation
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
Labels: Bug
