Repository MahApps/MahApps.Metro, pull requests merged in 2019-09, with the labels that each got.

#3555 Add TextAlignment to DataGridNumericUpDownColumn
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
  src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
  src/MahApps.Metro/Themes/NumericUpDown.xaml
Labels: Bug Fix

#3583 Renamed SemiTransparentGrey to SemiTransparentGray
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
Labels: Breaking Change

#3597 Fix creating a MetroWindow in a different thread
  src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/Themes/MetroWindow.xaml
Labels: Bug Fix

#3610 (GH-3349) Fix disable content of ToggleButton & Button when using circle style
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
Labels: Bug Fix

#3613 Add a Style for the GridSplitter-Control
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SplitViewExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/MahApps.Metro.csproj
  src/MahApps.Metro/Styles/Controls.GridSplitter.xaml
  src/MahApps.Metro/Styles/Controls.xaml
  src/MahApps.Metro/Styles/VS/ListBox.xaml
Labels: Feature
