Repository MahApps/MahApps.Metro, pull requests merged in 2019-05, with the labels that each got.

#3490 (GH-3457) Allow cancelling the item click for HamburgerMenu items
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.EventArgs.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs
Labels: Feature

#3491 (GH-3434) Add new HamburgerMenuSeparatorItem for HamburgerMenu
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuCreatorsUpdate.xaml
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemCollection.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemStyleSelector.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuSeparatorItem.cs
  src/MahApps.Metro/Themes/HamburgerMenu.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Feature

#3505 housekeeping: enable sponsorship button
  .github/FUNDING.yml
Labels: housekeeping

#3503 Improvement for title bar and window commands
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/WindowCommands.cs
  src/MahApps.Metro/Themes/MetroWindow.xaml
  src/MahApps.Metro/Themes/WindowCommands.xaml
Labels: Breaking Change

#3511 Change window commands overlay behavior after title bar changes (GH-3503)
  .gitignore
  src/Directory.Build.Props
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/MetroWindowHelpers.cs
  src/MahApps.Metro/Controls/OverlayBehavior.cs
  src/MahApps.Metro/Controls/WindowCommandsOverlayBehavior.cs
  src/MahApps.Metro/MahApps.Metro.csproj
  src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
  src/Mahapps.Metro.Tests/Tests/FlyoutTest.cs
  src/Mahapps.Metro.Tests/Tests/MetroWindowTest.cs
Labels: Breaking Change

#3514 Use TabControlEx from ControlzEx as base class for BaseMetroTabControl
  .gitignore
  paket.lock
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml.cs
  src/MahApps.Metro/Controls/MetroTabControl.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.cs
  src/MahApps.Metro/Themes/MetroTabControl.xaml
Labels: Breaking Change
