Repository MahApps/MahApps.Metro, pull requests merged in 2019-11, with the labels that each got.

#3666 Fix theme based styling for WindowCommands and WindowButtonCommands
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml
  src/MahApps.Metro/Controls/MetroWindowHelpers.cs
  src/MahApps.Metro/Controls/SplitButton.cs
  src/MahApps.Metro/Styles/Clean/CleanWindow.xaml
  src/MahApps.Metro/Styles/Clean/CleanWindowButtonCommands.xaml
  src/MahApps.Metro/Styles/Clean/CleanWindowButtons.xaml
  src/MahApps.Metro/Styles/Clean/CleanWindowCommands.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/Styles/VS/Colors.xaml
  src/MahApps.Metro/ThemeManager/Theme.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.cs
  src/MahApps.Metro/ThemeManager/ThemeType.cs
  src/MahApps.Metro/Themes/DropDownButton.xaml
  src/MahApps.Metro/Themes/SplitButton.xaml
  src/MahApps.Metro/Themes/WindowButtonCommands.xaml
  src/MahApps.Metro/Themes/WindowCommands.xaml
  src/Mahapps.Metro.Tests/TestApp.xaml.cs
  src/Mahapps.Metro.Tests/TestHelpers/TestHost.cs
  src/Mahapps.Metro.Tests/TestHelpers/WindowHelpers.cs
  src/Mahapps.Metro.Tests/Tests/CleanWindowTest.cs
  src/Mahapps.Metro.Tests/Views/CleanWindow.xaml
Labels: Breaking Change

#3664 Add an OverlayBrush to the SplitView
  src/MahApps.Metro/Controls/SplitView/SplitView.cs
  src/MahApps.Metro/Themes/SplitView.xaml
Labels: Feature

#3672 Improve DataGrid column styling
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
  src/MahApps.Metro/Controls/Helper/DataGridCellHelper.cs
  src/MahApps.Metro/Controls/Helper/DataGridHelper.cs
  src/MahApps.Metro/Controls/Helper/DataGridRowHelper.cs
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
Labels: Breaking Change

#3675 Fix SplitButton contents disappearing on subsequent clicks
  src/MahApps.Metro/Controls/SplitButton.cs
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Themes/SplitButton.xaml
Labels: Breaking Change

#3679 Fix padding for input controls
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
  src/MahApps.Metro/Themes/HotKeyBox.xaml
  src/MahApps.Metro/Themes/NumericUpDown.xaml
Labels: Breaking Change

#3678 Handle NumericUpDown percentage StringFormat correctly
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/Controls/NumericUpDown.cs
  src/Mahapps.Metro.Tests/Tests/NumericUpDownFixture.cs
  src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
Labels: Breaking Change

#3682 Share watermark text message storyboards
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Styles/Shared.xaml
Labels: Breaking Change

#3683 Add explicit WindowCommand styles for Button/ToggleButton
  src/MahApps.Metro/Themes/WindowCommands.xaml
Labels: Feature

#3685 Improve NumericUpDown example
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml.cs
Labels: Improvement

#3688 Add CheckMark for VS MenuItem
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
  src/MahApps.Metro/Styles/VS/Colors.xaml
  src/MahApps.Metro/Styles/VS/Menu.xaml
Labels: Bug Fix

#3689 Publish explicit WindowCommand controls styles
  src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/WindowCommands.cs
  src/MahApps.Metro/Controls/WindowCommandsItem.cs
  src/MahApps.Metro/Converters/ToLowerConverter.cs
  src/MahApps.Metro/Converters/ToUpperConverter.cs
  src/MahApps.Metro/Styles/Controls.xaml
  src/MahApps.Metro/Themes/WindowCommands.xaml
Labels: Breaking Change

#3692 Add new HamburgerMenuHeaderItem
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuCreatorsUpdate.xaml
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuHeaderItem.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemStyleSelector.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuHeaderItem.cs
  src/MahApps.Metro/Themes/HamburgerMenu.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Feature

#3691 Add helper for multi selected binding for Listbox/Multiselector controls
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/Helper/MultiSelectorHelper.cs
Labels: Feature

#3649 Updates MA.M font namespaces to be more uniform
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ColorExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/HamburgerMenuRipple/HamburgerMenuRipple.xaml
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Controls.Calendar.xaml
  src/MahApps.Metro/Styles/Controls.CheckBox.xaml
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.ContextMenu.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.GroupBox.xaml
  src/MahApps.Metro/Styles/Controls.Page.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.RadioButton.xaml
  src/MahApps.Metro/Styles/Controls.StatusBar.xaml
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Styles/Controls.TextBlock.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Styles/Controls.ToggleSwitch.xaml
  src/MahApps.Metro/Styles/Controls.Tooltip.xaml
  src/MahApps.Metro/Styles/Fonts.xaml
  src/MahApps.Metro/Styles/VS/Colors.xaml
  src/MahApps.Metro/Styles/VS/Menu.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
  src/MahApps.Metro/Themes/DropDownButton.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/HotKeyBox.xaml
  src/MahApps.Metro/Themes/MetroHeader.xaml
  src/MahApps.Metro/Themes/MetroWindow.xaml
  src/MahApps.Metro/Themes/NumericUpDown.xaml
  src/MahApps.Metro/Themes/Pivot.xaml
  src/MahApps.Metro/Themes/SplitButton.xaml
  src/MahApps.Metro/Themes/ToggleSwitch.xaml
Labels: Breaking Change

#3697 Moved attached properties related to Header under HeaderedControlHelper
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuSample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
  src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
  src/MahApps.Metro/Controls/Helper/HeaderedControlHelper.cs
  src/MahApps.Metro/Styles/Clean/CleanGroupBox.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.GroupBox.xaml
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Styles/Controls.ToggleSwitch.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
  src/MahApps.Metro/Styles/VS/GroupBox.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/MetroHeader.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
  src/MahApps.Metro/Themes/ToggleSwitch.xaml
  src/MahApps.Metro/Themes/WindowButtonCommands.xaml
Labels: Breaking Change

#3696 DatePicker enhancements
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/Helper/DatePickerHelper.cs
  src/MahApps.Metro/Controls/Helper/MahAppsCommands.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
Labels: Feature

#3695 Improved external dialog to no longer extend onto other monitors
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
  src/MahApps.Metro/Controls/Extensions.cs
  src/MahApps.Metro/Controls/WinApiHelper.cs
Labels: Bug Fix

#3703 Fix Cake build error
  build.ps1
Labels: Bug Fix

#3704 Allow using the DropDownButton without a dropdown menu
  src/MahApps.Metro/Controls/DropDownButton.cs
Labels: Bug Fix

#3706 Use ContentControlEx at Labels Template to enable ContentCharacterCasing
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
  src/MahApps.Metro/Styles/Controls.Label.xaml
Labels: Feature
