Repository MahApps/MahApps.Metro, pull requests merged in 2019-10, with the labels that each got.

#3619 HamburgerMenu: Allow using own items together with the new HamburgerMenuItemStyleSelector
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemStyleSelector.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuSeparatorItem.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuItem.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuSeparatorItem.cs
Labels: Hacktoberfest

#3624 Fix that makes ContextMenu work with VS theme
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
  src/MahApps.Metro/Styles/VS/Button.xaml
  src/MahApps.Metro/Styles/VS/Colors.xaml
  src/MahApps.Metro/Styles/VS/Menu.xaml
  src/MahApps.Metro/Styles/VS/Styles.xaml
  src/MahApps.Metro/Styles/VS/TextBox.xaml
Labels: Hacktoberfest

#3625 Add the ability to control button font size in dialogs via MetroDialogSettings
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/MetroDialogSettings.cs
  src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
  src/MahApps.Metro/Styles/Fonts.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Labels: Hacktoberfest

#3626 Add a hidden state for TransitioningContentControl
  src/MahApps.Metro/Controls/TransitioningContentControl.cs
  src/MahApps.Metro/Themes/TransitioningContentControl.xaml
Labels: Hacktoberfest

#3627 Use CornerRadius for some controls
  src/MahApps.Metro/Styles/Controls.CheckBox.xaml
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
Labels: Hacktoberfest

#3631 More CornerRadius usage
  src/MahApps.Metro/Converters/CornerRadiusBindingConverter.cs
  src/MahApps.Metro/Converters/RadiusType.cs
  src/MahApps.Metro/Converters/ThicknessBindingConverter.cs
  src/MahApps.Metro/Converters/ThicknessToDoubleConverter.cs
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.GroupBox.xaml
  src/MahApps.Metro/Styles/Controls.ListBox.xaml
  src/MahApps.Metro/Styles/Controls.ListView.xaml
  src/MahApps.Metro/Styles/Controls.TreeView.xaml
  src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml
Labels: Hacktoberfest

#3637 Added AttachedProperty CornerRadius to all Buttons (optional)
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/VS/Button.xaml
Labels: Hacktoberfest

#3636 Rename GroupBoxHelper to HeaderedControlHelper and introduced a new AttachedProperty HeaderBackground
  src/MahApps.Metro/Controls/Helper/GroupBoxHelper.cs
  src/MahApps.Metro/Controls/Helper/HeaderedControlHelper.cs
  src/MahApps.Metro/Styles/Clean/CleanGroupBox.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.GroupBox.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
  src/MahApps.Metro/Styles/VS/GroupBox.xaml
  src/MahApps.Metro/Themes/MetroHeader.xaml
Labels: Breaking Change

#3648 (GH-3646) Fix broken RichTextBox
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
Labels: Bug Fix

#3645 Fix issue with P, % and ‰ used in StringFormat outside of the format item
  src/MahApps.Metro/Controls/NumericUpDown.cs
  src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
Labels: Bug Fix

#3650 Subsequent changes after GH-3552
  src/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
Labels: Bug Fix
