Repository MahApps/MahApps.Metro, pull requests merged in 2019-07, with the labels that each got.

#3546 [GH-3544] Add null check for Application.Current
  src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.cs
Labels: Bug Fix

#3540 Added a Trigger to MouseOver Property of ValidationMessage
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
  src/MahApps.Metro/Controls/Helper/ValidationHelper.cs
  src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml
Labels: Feature

#3550 Add delegate to customize external dialog window
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Labels: Feature

#3557 (GH-2384) Subsequent changes after #3552 Update resource names
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Views/Flyouts/FlyoutBottomView.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Views/Flyouts/FlyoutTopView.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/DynamicFlyout.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/ShowcaseFlyout.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
  src/MahApps.Metro/Controls/MetroNavigationWindow.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.Scrollbars.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Styles/Controls.Toolbar.xaml
  src/MahApps.Metro/Styles/Controls.xaml
  src/MahApps.Metro/Styles/VS/Button.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
  src/MahApps.Metro/Styles/VS/GroupBox.xaml
  src/MahApps.Metro/Styles/VS/ListBox.xaml
  src/MahApps.Metro/Styles/VS/Menu.xaml
  src/MahApps.Metro/Styles/VS/ScrollBar.xaml
  src/MahApps.Metro/Styles/VS/Styles.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Styles/VS/TextBox.xaml
  src/MahApps.Metro/Styles/VS/Window.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
  src/MahApps.Metro/Themes/NumericUpDown.xaml
  src/MahApps.Metro/Themes/RangeSlider.xaml
  src/MahApps.Metro/Themes/WindowButtonCommands.xaml
  src/Mahapps.Metro.Tests/Views/ButtonWindow.xaml
Labels: Breaking Change

#3560 (GH-2384) Subsequent change after #3552 Update colors names
  src/MahApps.Metro/Styles/Themes/GeneratorParameters.json
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
Labels: Breaking Change
