Repository MahApps/MahApps.Metro, pull requests merged in 2019-01, with the labels that each got.

#3417 Fixing multiple compile issues
  src/MahApps.Metro/MahApps.Metro.csproj
Labels: Internal Refactoring

#3418 Syncing ThemeManager code with Fluent.Ribbon
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/Flyout.cs
  src/MahApps.Metro/ThemeManager/Theme.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.StyleKeys.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.cs
  src/Mahapps.Metro.Tests/TestHelpers/AutomationTestBase.cs
  src/Mahapps.Metro.Tests/Tests/ThemeManagerTest.cs
Labels: Internal Refactoring

#3440 Add DataTemplates for range slider auto tool tip values
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/Sliders.xaml
  src/MahApps.Metro/Controls/RangeSlider.cs
Labels: Breaking Change

#3441 ScrollViewer end of scroll command
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/Helper/ScrollViewerHelper.cs
  src/MahApps.Metro/Controls/TreeHelper.cs
Labels: Feature

#3444 Fix for HamburgerMenu item selection
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/Sliders.xaml
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.cs
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Bug
