Repository MahApps/MahApps.Metro, pull requests merged in 2020-02, with the labels that each got.

#3736 Add RadioButton Windows 10 Style
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro/Controls/Helper/RadioButtonHelper.cs
  src/MahApps.Metro/Styles/Controls.CheckBox.xaml
  src/MahApps.Metro/Styles/Controls.RadioButton.xaml
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
Labels: Feature

#3739 Fix not updating child when using TiltBehavior, after changing accent or theme
  src/MahApps.Metro/Behaviors/TiltBehavior.cs
  src/MahApps.Metro/Controls/LayoutInvalidationCatcher.cs
  src/MahApps.Metro/Controls/Planerator.cs
Labels: Bug Fix

#3743 Improve ToolbarButtonStyle
  src/MahApps.Metro/Styles/Controls.Toolbar.xaml
Labels: Breaking Change
