Repository MahApps/MahApps.Metro, pull requests merged in 2020-10, with the labels that each got.

#3925 Update Binding before executing the command of "TextBoxHelper.ButtonCommand"
  src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
Labels: Improvement

#3917 [RFC] Updates the MahApps example list
  readme.md
Labels: Documentation

#3914 Add DecimalPointCorrection property to DataGridNumericUpDownColumn
  src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
Labels: Feature

#3941 Fix Menu & ContextMenu issues
  src/MahApps.Metro/Styles/Controls.ContextMenu.xaml
  src/MahApps.Metro/Styles/Controls.MenuItem.xaml
  src/MahApps.Metro/Styles/Controls.Shadows.xaml
  src/MahApps.Metro/Styles/Controls.Shared.xaml
  src/MahApps.Metro/Styles/Themes/GeneratorParameters.json
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/Styles/VS/ContextMenu.xaml
  src/MahApps.Metro/Styles/VS/Controls.xaml
  src/MahApps.Metro/Styles/VS/MenuItem.xaml
  src/MahApps.Metro/Styles/VS/Shadows.xaml
  src/MahApps.Metro/Themes/MetroWindow.xaml
Labels: Bug Fix

#3942 Fix/Update ItemHelper property usage
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/HamburgerMenuRipple/HamburgerMenuRipple.xaml
  src/MahApps.Metro/Controls/Helper/ItemHelper.cs
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.ListBox.xaml
  src/MahApps.Metro/Styles/Controls.ListView.xaml
  src/MahApps.Metro/Styles/Controls.TreeView.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Bug Fix

#3945 Fix not displaying validation error on Flyout
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
  src/MahApps.Metro/Controls/Flyout.cs
Labels: Bug Fix

#3946 (GH-3944) Use BeginInvoke to prevent deadlocks in multithreaded cases
  src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
Labels: Bug Fix

#3948 Fix overriding of ItemsControl items background
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro/Controls/Helper/ItemHelper.cs
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.ListBox.xaml
  src/MahApps.Metro/Styles/Controls.ListView.xaml
  src/MahApps.Metro/Styles/Controls.TreeView.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Bug Fix

#3949 Allow GroupStyle for DropDownButton
  src/MahApps.Metro/Controls/DropDownButton.cs
  src/MahApps.Metro/Themes/DropDownButton.xaml
Labels: Bug Fix

#3950 Allow overriding Watermark Storyboards and floating text foreground
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
Labels: Bug Fix

#3956 Do not use DynamicResource to get Storyboards inside Triggers
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Controls/StartupTasks.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Controls/ViewLocator.cs
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
Labels: Bug Fix

#3960 Fix not showing alternation background when ItemsControl is disabled
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/HamburgerMenuRipple/HamburgerMenuRipple.xaml
  src/MahApps.Metro/Styles/Controls.ComboBox.xaml
  src/MahApps.Metro/Styles/Controls.ListBox.xaml
  src/MahApps.Metro/Styles/Controls.ListView.xaml
  src/MahApps.Metro/Themes/DropDownButton.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Bug Fix
