Repository MahApps/MahApps.Metro, pull requests merged in 2020-06, with the labels that each got.

#3835 (GH-3821) Fix Fill and Stroke brush for RadioButton's outer ellipse
  src/MahApps.Metro/Styles/Controls.RadioButton.xaml
Labels: Bug Fix

#3836 (GH-3827) Change Check Background for CheckBox
  src/MahApps.Metro/Styles/Controls.CheckBox.xaml
Labels: Bug Fix

#3837 (GH-3817) Fix coercing of OpenPaneLength at HamburgerMenu
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
Labels: Bug Fix

#3846 Fixed duplicated instruction
  src/MahApps.Metro/Controls/Flyout.cs
Labels: Bug Fix

#3841 (GH-3840) DataGrid auto generated column styles
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
  src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
  src/MahApps.Metro/Controls/Helper/DataGridColumnStylesHelperExtension.cs
  src/MahApps.Metro/Controls/Helper/DataGridHelper.cs
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.Hyperlink.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Styles/Controls.xaml
  src/MahApps.Metro/Themes/DropDownButton.xaml
Labels: Bug Fix

#3854 (GH-3838) Fix Highlight color for Blue and Purple
  .editorconfig
  src/MahApps.Metro/Styles/Themes/GeneratorParameters.json
Labels: Bug Fix

#3850 [NumericUpDown] Always use the current cultures decimal separator
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/DecimalPointCorrectionMode.cs
  src/MahApps.Metro/Controls/NumericUpDown.cs
Labels: Feature

#3858 Add Flat slider resource keys for MinWidth and MinHeight
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/Styles/Controls.FlatSlider.xaml
Labels: Feature

#3860 (GH-3859) Allow own ViewModel collection for HamburgerMenu ItemsSource
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenuListBox.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuItemBase.cs
  src/MahApps.Metro/Themes/Generic.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Bug Fix

#3856 (GH-3839) Allow setting AutomationProperties for HamburgerMenuItem
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuCreatorsUpdate.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuDefault.xaml
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.EventArgs.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.HamburgerButton.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Options.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenuListBox.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuItem.cs
  src/MahApps.Metro/Converters/HamburgerMenuItemAccessibleConverter.cs
  src/MahApps.Metro/Themes/HamburgerMenu.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Feature

#3862 Fix not showing external dialogs inside Powershell scripts
  src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
  src/MahApps.Metro/Controls/Flyout.cs
  src/MahApps.Metro/Controls/MetroWindowHelpers.cs
Labels: Bug Fix

#3864 Added new attached properties to the RadioButtonHelper
  src/MahApps.Metro/Controls/Helper/RadioButtonHelper.cs
  src/MahApps.Metro/Styles/Controls.RadioButton.xaml
Labels: Feature

#3866 (GH-3865) Fix InvalidOperationException when open a dialog over a child window
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
Labels: Bug Fix

#3869 Use BooleanBoxes for better dependency properties performance
  src/MahApps.Metro/Actions/CloseFlyoutAction.cs
  src/MahApps.Metro/Actions/CommandTriggerAction.cs
  src/MahApps.Metro/Behaviors/PasswordBoxBindingBehavior.cs
  src/MahApps.Metro/Behaviors/ReloadBehavior.cs
  src/MahApps.Metro/Behaviors/TiltBehavior.cs
  src/MahApps.Metro/Controls/ClipBorder.cs
  src/MahApps.Metro/Controls/ContentControlEx.cs
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
  src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml.cs
  src/MahApps.Metro/Controls/DropDownButton.cs
  src/MahApps.Metro/Controls/FlipView.cs
  src/MahApps.Metro/Controls/Flyout.cs
  src/MahApps.Metro/Controls/FlyoutsControl.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
  src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
  src/MahApps.Metro/Controls/Helper/DataGridHelper.cs
  src/MahApps.Metro/Controls/Helper/ScrollViewerHelper.cs
  src/MahApps.Metro/Controls/Helper/TabControlHelper.cs
  src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
  src/MahApps.Metro/Controls/Helper/ValidationHelper.cs
  src/MahApps.Metro/Controls/HotKeyBox.cs
  src/MahApps.Metro/Controls/MetroContentControl.cs
  src/MahApps.Metro/Controls/MetroTabControl.cs
  src/MahApps.Metro/Controls/MetroTabItem.cs
  src/MahApps.Metro/Controls/MetroThumbContentControl.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/NumericUpDown.cs
  src/MahApps.Metro/Controls/ProgressRing.cs
  src/MahApps.Metro/Controls/RangeSlider.cs
  src/MahApps.Metro/Controls/SplitButton.cs
  src/MahApps.Metro/Controls/SplitView/SplitView.cs
  src/MahApps.Metro/Controls/Tile.cs
  src/MahApps.Metro/Controls/TimePicker/DateTimePicker.cs
  src/MahApps.Metro/Controls/TimePicker/TimePickerBase.cs
  src/MahApps.Metro/Controls/ToggleSwitch.cs
  src/MahApps.Metro/Controls/TransitioningContentControl.cs
  src/MahApps.Metro/Controls/WindowCommands.cs
  src/MahApps.Metro/Controls/WindowCommandsItem.cs
  src/MahApps.Metro/ValueBoxes/BooleanBoxes.cs
Labels: Improvement
