Repository MahApps/MahApps.Metro, pull requests merged in 2020-04, with the labels that each got.

#3771 Switching to ThemeManager from ControlzEx
  NuGet.Config
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Behaviors/TiltBehavior.cs
  src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
  src/MahApps.Metro/Controls/Flyout.cs
  src/MahApps.Metro/Controls/FlyoutTheme.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/MetroWindowHelpers.cs
  src/MahApps.Metro/Controls/Theme.cs
  src/MahApps.Metro/Controls/WindowButtonCommands.cs
  src/MahApps.Metro/Controls/WindowCommands.cs
  src/MahApps.Metro/MahApps.Metro.csproj
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/ThemeManager/Theme.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.StyleKeys.cs
  src/MahApps.Metro/ThemeManager/ThemeManager.cs
  src/MahApps.Metro/ThemeManager/ThemeType.cs
  src/MahApps.Metro/Themes/Generic.xaml
  src/MahApps.Metro/Themes/Tile.xaml
  src/MahApps.Metro/Theming/MahAppsLibraryThemeProvider.cs
  src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
  src/Mahapps.Metro.Tests/TestHelpers/AutomationTestBase.cs
  src/Mahapps.Metro.Tests/TestHelpers/ThemeHelper.cs
  src/Mahapps.Metro.Tests/Tests/CleanWindowTest.cs
  src/Mahapps.Metro.Tests/Tests/FlyoutTest.cs
  src/Mahapps.Metro.Tests/Tests/ThemeManagerTest.cs
Labels: Breaking Change

#3781 Removing test that already exist in ControlzEx
  src/MahApps.Metro.sln
  src/Mahapps.Metro.Tests/Tests/ThemeManagerTest.cs
Labels: Housekeeping

#3782 Add IsVisible property to HambugerMenuItemBase
  src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Labels: Feature

#3785 (GH-3783) Add OnCommand and OffCommand to ToggleSwitch
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/CommandHelpers.cs
  src/MahApps.Metro/Controls/ToggleSwitch.cs
Labels: Feature
