Repository MahApps/MahApps.Metro, pull requests merged in 2020-05, with the labels that each got.

#3788 Fix for renamed options property in RuntimeThemeGenerator
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
Labels: Bug Fix

#3775 (GH-3746) Fix Date and Time selection and other improvements for DateTimePicker
  .editorconfig
  src/MahApps.Metro.sln
  src/MahApps.Metro/Controls/TimePicker/DateTimePicker.cs
  src/MahApps.Metro/Controls/TimePicker/TimePicker.cs
  src/MahApps.Metro/Controls/TimePicker/TimePickerBase.cs
  src/MahApps.Metro/Controls/TimePicker/TimePickerBaseSelectionChangedEventArgs.cs
  src/MahApps.Metro/Themes/DateTimePicker.xaml
Labels: Bug Fix

#3790 Added a way to use DataTemplate in BadgedControl
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro/Converters/SizeToCornerRadiusConverter.cs
  src/MahApps.Metro/Themes/Badged.xaml
Labels: Feature

#3794 (GH-3356, GH-2093) Fix validation popup position after scrolling inside a ScrollViewer
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
  src/MahApps.Metro/Controls/Flyout.cs
  src/MahApps.Metro/Controls/MetroContentControl.cs
  src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml
  src/MahApps.Metro/Themes/Badged.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
  src/MahApps.Metro/Themes/MetroContentControl.xaml
Labels: Bug Fix

#3793 Resizeable SplitViewPane
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuCreatorsUpdate.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuDefault.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SplitViewExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/HamburgerMenuRipple/HamburgerMenuRipple.xaml
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.HamburgerButton.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Options.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
  src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.cs
  src/MahApps.Metro/Controls/SplitView/GridLengthAnimation.cs
  src/MahApps.Metro/Controls/SplitView/SplitView.cs
  src/MahApps.Metro/Controls/SplitView/SplitViewTemplateSettings.cs
  src/MahApps.Metro/Themes/HamburgerMenu.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
  src/MahApps.Metro/Themes/SplitView.xaml
Labels: Feature

#3805 Add DataGrid GroupStyle and fix grouping errors
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ValueConverter/ItemCountConverter.cs
  src/MahApps.Metro/Controls/Helper/ExpanderHelper.cs
  src/MahApps.Metro/Controls/NumericUpDown.cs
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
Labels: Bug Fix

#3808 Fix RangeSlider Upper/Lower value coercion and value changed events
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/Sliders.xaml.cs
  src/MahApps.Metro/Controls/RangeParameterChangedEventArgs.cs
  src/MahApps.Metro/Controls/RangeSelectionChangedEventArgs.cs
  src/MahApps.Metro/Controls/RangeSlider.cs
Labels: Breaking Change

#3804 Fixed Validation Tooltip that never shows up.
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
Labels: Bug Fix

#3816 (GH-3812) Fix wrong space for Expander before expanded
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
  src/MahApps.Metro/Controls/Helper/ExpanderHelper.cs
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
Labels: Bug Fix

#3819 Fix parent IsEnabled behavior for DropDownButton and SplitButton
  src/MahApps.Metro/Controls/DropDownButton.cs
  src/MahApps.Metro/Controls/SplitButton.cs
  src/MahApps.Metro/Themes/DropDownButton.xaml
  src/MahApps.Metro/Themes/SplitButton.xaml
  src/Mahapps.Metro.Tests/Tests/ButtonTest.cs
  src/Mahapps.Metro.Tests/Views/ButtonWindow.xaml
Labels: Bug Fix

#3830 (GH-3829) Fix DateTimePicker BindingExpression errors
  src/MahApps.Metro/Accessibility/AccessibilitySwitches.cs
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
Labels: Bug Fix
