Repository MahApps/MahApps.Metro, pull requests merged in 2021-06, with the labels that each got.

#4119 Update FontIcon and add new PathIcon control
  src/MahApps.Metro/Controls/FontIcon.cs
  src/MahApps.Metro/Controls/IconElement.cs
  src/MahApps.Metro/Controls/MetroNavigationWindow.xaml
  src/MahApps.Metro/Controls/PathIcon.cs
  src/MahApps.Metro/Styles/Controls.CheckBox.xaml
  src/MahApps.Metro/Themes/FontIcon.xaml
  src/MahApps.Metro/Themes/Generic.xaml
  src/MahApps.Metro/Themes/PathIcon.xaml
Labels: Feature

#4121 Remove MahApps.Styles.ContentControl.PathIcon and use PathIcon instead
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/ShowcaseFlyout.xaml
  src/MahApps.Metro/Controls/Icons/FontIcon.cs
  src/MahApps.Metro/Controls/Icons/IconElement.cs
  src/MahApps.Metro/Controls/Icons/PathIcon.cs
  src/MahApps.Metro/Styles/Controls.ContentControl.xaml
  src/MahApps.Metro/Styles/Controls.DatePicker.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Styles/Controls.TextBox.xaml
  src/MahApps.Metro/Themes/DateTimePicker.xaml
  src/MahApps.Metro/Themes/DropDownButton.xaml
  src/MahApps.Metro/Themes/Flyout.xaml
  src/MahApps.Metro/Themes/HamburgerMenu.xaml
  src/MahApps.Metro/Themes/SplitButton.xaml
Labels: Breaking Change

#4122 Fix position of ValidationErrorTemplate together with ValidatesOnExceptions
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
Labels: Bug Fix

#4123 Fix getting the wrong Ancestor (ScrollViewer) at CustomValidationPopup
  src/MahApps.Metro/Controls/CustomValidationPopup.cs
  src/MahApps.Metro/Controls/TreeHelper.cs
Labels: Bug Fix

#4129 Add option to close ColorPicker on selected color changed
  src/MahApps.Metro/Controls/ColorPicker/ColorPicker.cs
Labels: Feature

#4003 Make NumericUpDown more stylable
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
  src/MahApps.Metro/Controls/NumericUpDown.cs
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
  src/MahApps.Metro/Styles/Controls.xaml
  src/MahApps.Metro/Themes/Generic.xaml
  src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
  src/MahApps.Metro/Themes/NumericUpDown.xaml
Labels: Feature

#4133 Fix wrong translation for color names
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ColorPickerExample.xaml
  src/MahApps.Metro/Controls/ColorPicker/ColorHelper.cs
  src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
Labels: Breaking Change

#4142 Add new dialog brush keys
  src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
  src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Labels: Breaking Change

#4143 Add new CharacterCasing keys
  src/MahApps.Metro/Styles/Clean/WindowCommands.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
  src/MahApps.Metro/Styles/Controls.DataGrid.xaml
  src/MahApps.Metro/Styles/Controls.Expander.xaml
  src/MahApps.Metro/Styles/Controls.GroupBox.xaml
  src/MahApps.Metro/Styles/Controls.ListView.xaml
  src/MahApps.Metro/Styles/Fonts.xaml
  src/MahApps.Metro/Styles/VS/Expander.xaml
  src/MahApps.Metro/Styles/VS/GroupBox.xaml
  src/MahApps.Metro/Themes/ColorPicker/ColorEyeDropper.xaml
  src/MahApps.Metro/Themes/ColorPicker/ColorPalette.xaml
  src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
  src/MahApps.Metro/Themes/HotKeyBox.xaml
  src/MahApps.Metro/Themes/WindowCommands.xaml
  src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
Labels: Feature
