Repository MahApps/MahApps.Metro, pull requests merged in 2022-02, with the labels that each got.

#4259 Fix MultiSelectionComboBox SelectedItems Duplicate
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/MultiSelectionComboBoxExample.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/Models/Animals.cs
  src/MahApps.Metro/Controls/Helper/MultiSelectorHelper.cs
  src/MahApps.Metro/Controls/MultiSelectionComboBox/MultiSelectionComboBox.cs
  src/Mahapps.Metro.Tests/Tests/MultiSelectorHelperTests.Fixture.cs
  src/Mahapps.Metro.Tests/Tests/MultiSelectorHelperTests.cs
  src/Mahapps.Metro.Tests/Views/MultiSelectorHelperTestWindow.xaml
Labels: Bug Fix

#4262 Allow setting the CornerRadius for the HotKeyBox
  src/MahApps.Metro/Themes/HotKeyBox.xaml
Labels: Feature

#4264 Added FallbackValue in XAML for Calendar control styles:
  src/MahApps.Metro/Styles/Controls.Calendar.xaml
Labels: Bug Fix

#4268 Remove flyout accent theme
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/ViewModels/Flyouts/FlyoutLeftViewModel.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/ViewModels/Flyouts/FlyoutTopViewModel.cs
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml.cs
  src/MahApps.Metro/Controls/Flyout.cs
  src/MahApps.Metro/Controls/FlyoutTheme.cs
Labels: Breaking Change

#4269 Allow set the CornerRadius for TabItem
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
Labels: Feature

#4270 Allow set the CornerRadius for TabControl
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Styles/VS/TabControl.xaml
  src/MahApps.Metro/Themes/MetroTabControl.xaml
Labels: Feature

#4271 Allow set TabContol/TabItem Underline properties without to redefine the full style
  src/MahApps.Metro/Controls/Helper/TabControlHelper.cs
  src/MahApps.Metro/Styles/Controls.TabControl.xaml
  src/MahApps.Metro/Themes/MetroTabControl.xaml
  src/MahApps.Metro/Themes/MetroTabItem.xaml
Labels: Feature

#4272 Allow changing the ListView grid header reorder indicator brush
  src/MahApps.Metro/Controls/GridViewHeaderRowPresenterEx.cs
  src/MahApps.Metro/Controls/Helper/ItemHelper.cs
  src/MahApps.Metro/Styles/Controls.ListView.xaml
Labels: Feature
