Repository MahApps/MahApps.Metro, pull requests merged in 2023-02, with the labels that each got.

#4380 Fixes #4379 by using NonClientControlProperties where required
  src/MahApps.Metro/Styles/Clean/WindowButtons.xaml
  src/MahApps.Metro/Styles/Controls.Buttons.xaml
Labels: Bug Fix

#4383 Allow to reset the window settings
  src/Directory.packages.props
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml.cs
  src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/WinApiHelper.cs
  src/MahApps.Metro/Controls/WindowSettings.cs
Labels: Feature

#4384 Remove methods to show an existing dialog externally
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
  src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
  src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
Labels: Breaking Change
