Repository MahApps/MahApps.Metro, pull requests merged in 2023-12, with the labels that each got.

#4443 Replacing .NET versions
  .github/workflows/ci.yml
  appveyor.yml
  src/Directory.Build.Props
  src/Directory.Build.Targets
  src/Directory.packages.props
  src/MahApps.Metro/Directory.Build.Targets
  src/MahApps.Metro/Directory.Build.props
  src/MahApps.Metro/MahApps.Metro.csproj
  src/MahApps.Metro/MahAppsException.cs
  src/Mahapps.Metro.Tests/Tests/MathConverterTests.cs
  src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
  src/global.json
Labels: Breaking Change

#4407 when restoring window size use the DPI scale factor
  src/MahApps.Metro/Controls/WinApiHelper.cs
Labels: Bug Fix

#4446 Add new property CloseOnIconDoubleClick to MetroWindow
  src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
  src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
  src/MahApps.Metro/Controls/MetroWindow.cs
  src/MahApps.Metro/Controls/WindowButtonCommands.cs
  src/MahApps.Metro/Native/PInvokeExtensions.cs
  src/MahApps.Metro/Native/WinApiHelper.cs
  src/MahApps.Metro/NativeMethods.txt
Labels: Feature
